### ISSUE TITLE
UPDATE - Takedown Request from BNY Mellon Information Security Division

### ISSUE THREAD

**Issue by theh0n3ybadg3r** [Shikhar447/Projects#1]
Good evening,

By way of introduction, my name is Nik Levitan and I represent Cyber Incident Response within BNY Mellon. This afternoon it was brought to our attention by one of our security research vendors that this repository within your personal GitHub project contains data that references BNY Mellon technical information including database connections with login credentials

The technical information contained within the repository represents a security risk to BNY Mellon as this information can be used by attackers to leverage access to our internal resources if we were to be compromised. While we understand that employees will use online repositories such as GitHub, employees are not permitted to post information referencing BNY Mellon details within these repositories.

As part of the remediation activities please can you remove Map Services directory, sub-directories and all files within those folders , including any cloned instances and local copies you may have on your personal device.

I thank you in advance for your cooperation in this matter.

Regards,

Nik

**Comment by shiiks** [comment]
Hello Nik,

Thank you for bringing this to my attention, I have removed those files which contains credentials.

Thanks
Shikhar

**Comment by theh0n3ybadg3r** [comment]
Hi Shikhar,

Thank you for your attention to this but your files still reference BNY Mellon. For example:

MyMap/target/classes/com/bnymellon
MyMap/target/m2e-wtp/web=resrouces/META-INF/maven/com.bnymellon.lnd.mapservices

In addition there are files within this locations that contain the word bnymellon and these need to be either removed or obfuscated. 

Again, thank you for your quick turnaround on this request.

Regards,

Nik

**Comment by theh0n3ybadg3r** [comment]
HI Shikhar,

I was reviewing GitHub content and I noticed that your repo still has references to our organization as per the above comments. Please could you assist me in remove this content completely?

Many Thanks,

Nik

**Comment by shiiks** [comment]
All references have been removed.
